-- vim.lsp.config('gdscript', {
--   cmd = vim.lsp.rpc.connect('127.0.0.1', 6005),
--   name = 'godot',
--   filetypes = { 'godot', 'gd', 'gdscript' },
--   root_markers = { '.git' },
-- })
--
-- vim.lsp.enable 'gdscript'
